import { Vessel } from "@/types/vessel";

export const placeholderFleet: Vessel[] = [
  {
    id: "vessel-01",
    name: "YF Golden Crest",
    description: "A 50-passenger electric catamaran built for coastal and harbour routes, designed for quiet, low-wake operation.",
    fullDescription: "The YF Golden Crest is YellowFleet's compact electric catamaran, purpose-built for coastal transfers, harbour connectivity, and short-hop passenger services. At 17 metres and rated for 50 passengers, it combines a lightweight aluminium hull with quiet electric propulsion — making it ideal for operators looking to replace diesel-powered vessels on high-frequency, short-distance routes. Its low draft and Class IV certification make it well-suited for sheltered coastal and inland waterway operations across Maharashtra and beyond.",
    capacity: 50,
    hull_material: "Aluminium",
    speed_knots: 12,
    hull_type: "Cat",
    class: "IV",
    length_m: 17,
    breadth_m: 5.6,
    draft_m: 0.8,
    air_draft_m: 4.2,
    freeboard_m: 0.8,
    dwt_t: 6.0,
    range_km: 0,
    image_url: "/images/vessels/golden-crest-1.png",
    images: [
      "/images/vessels/golden-crest-1.png",
      "/images/vessels/golden-crest-2.png",
      "/images/vessels/golden-crest-3.png",
      "/images/vessels/golden-crest-4.png",
      "/images/vessels/golden-crest-5.png",
      "/images/vessels/golden-crest-7.png",
    ],
    active: true,
  },
  {
    id: "vessel-02",
    name: "YF Ecowave",
    description: "A 100-passenger electric vessel engineered for high-frequency water metro and public transport operations.",
    fullDescription: "The YF Ecowave is YellowFleet's high-capacity workhorse — a 100-passenger electric catamaran designed for the demands of urban water metro systems and scheduled inter-coastal services. At 23 metres, it offers significantly more deck space than the Golden Crest while maintaining the operational simplicity of electric propulsion. Its aluminium construction keeps weight low, and at 18 knots it delivers the speed needed for time-sensitive commuter routes. Built to Class IV standards, the Ecowave is designed to operate in India's busiest coastal and inland waterway corridors.",
    capacity: 100,
    hull_material: "Aluminium",
    speed_knots: 18,
    hull_type: "Cat",
    class: "IV",
    length_m: 23,
    breadth_m: 6.4,
    draft_m: 1.1,
    air_draft_m: 4.2,
    freeboard_m: 1.0,
    dwt_t: 14,
    range_km: 0,
    image_url: "/images/vessels/ecowave-1.png",
    images: [
      "/images/vessels/ecowave-1.png",
      "/images/vessels/ecowave-2.png",
      "/images/vessels/ecowave-3.png",
      "/images/vessels/ecowave-4.png",
    ],
    active: true,
  },
  {
    id: "vessel-03",
    name: "YF Yellowtide",
    description: "A 100-passenger flagship electric catamaran built for large-scale sustainable marine passenger transport.",
    fullDescription: "The YF Yellowtide is YellowFleet's flagship vessel — a 100-passenger electric catamaran engineered for large-scale, government-grade marine passenger transport. At 21 metres with a 7.2 metre air draft, the Yellowtide is built for routes that demand both capacity and presence. Its aluminium catamaran hull delivers stability and efficiency at 18 knots, while zero-emission electric propulsion ensures compliance with India's clean transport goals. Designed for infrastructure-scale deployments — from water metro systems to inter-city marine corridors — the Yellowtide represents the full potential of electric marine mobility.",
    capacity: 100,
    hull_material: "Aluminium",
    speed_knots: 18,
    hull_type: "Cat",
    class: "IV",
    length_m: 21,
    breadth_m: 6.4,
    draft_m: 1.1,
    air_draft_m: 7.2,
    freeboard_m: 1.0,
    dwt_t: 14,
    range_km: 0,
    image_url: "/images/vessels/yellowtide-1.png",
    images: [
      "/images/vessels/yellowtide-1.png",
      "/images/vessels/yellowtide-2.png",
      "/images/vessels/yellowtide-3.png",
      "/images/vessels/yellowtide-4.png",
    ],
    active: true,
  },
];